"""Add portal submissions table

Revision ID: 6bbff1fcdc1b
Revises: dc60a10d6ae2
Create Date: 2025-09-30 16:34:14.954752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6bbff1fcdc1b'
down_revision: Union[str, Sequence[str], None] = 'dc60a10d6ae2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('portal_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'portal_data')
    # ### end Alembic commands ###
